version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
      - mongodb
    restart: always
    networks:
      - ecommerce-network
    env_file:
      - .env

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      NODE_ENV: development
      MONGO_URL: mongodb://mongodb:27017/ecommerce
      PORT: 4000
      STRIPE_SECRET_KEY: ${STRIPE_SECRET_KEY}
    depends_on:
      - mongodb
    restart: always
    networks:
      - ecommerce-network
    env_file:
      - .env

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - ecommerce-network

volumes:
  mongo-data:

networks:
  ecommerce-network:
    driver: bridge
